### ISSUE TITLE
Incorporation of ssNoob normalization?

### ISSUE THREAD

**Issue by axitamm** [zwdzwd/sesame#11]
Thank you for this amazing package! It is a great contribution!

Looking through the dye_bias.R code, I see that perhaps dyeBiasCorrMostBalanced function is the closest to the noob normalization in minfi (https://github.com/hansenlab/minfi/blob/master/R/preprocessNoob.R) where the reference used is the least worst (or the most balanced) sample in the batch. 

Is it possible to add the option of ssNoob in sesame? (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5408810/) where dyeMethod argument == "single", which reciprocates out the dye bias without using a reference?

Thank you,

**Comment by ttriche** [comment]
The `dyeBiasNL()` function does this (implements a somewhat more sophisticated version of ssNoob) using the mean intensity of signals in a sample as the pivot to equalize the red and green intensities.  It is a single-sample normalization approach, and it is also the default in the `sesamize()` function for rgSets.

**Comment by zwdzwd** [comment]
Sorry for having neglected this. Thanks @ttriche . Yes the noob is essentially single sample.
