### ISSUE TITLE
What is proper procedure?

### ISSUE THREAD

**Issue by ardan33** [zwdzwd/sesame#118]
Hi- I am new to methylation and using the mouse methylation array. I am also new-er to R Studio. I am able to get betas, sdfs, and qcs successfully- but I don't know if I am supposed to find new betas after the qcs code?? In my mind, there will be fewer beta values after quality control because I need to remove the poor quality ones? Or am I interpreting this wrong? Also- when and where does normalization occur? Thanks!

**Comment by zwdzwd** [comment]
You don't get new betas after qcs code. The QC just return summary numbers to inform the experiment quality. If you are looking for masking poorly performing probes, check qualityMask and detection p-value calling methods (like pOOBAH). These functions change the mask column of the SigDF and define whether beta values produced get NA. Hope that clarifies.

**Comment by ardan33** [comment]
Okay- that helps a lot! Thank you!!
