### ISSUE TITLE
Error when trying to plot intensities vs betas 

### ISSUE THREAD

**Issue by ardan33** [zwdzwd/sesame#119]
I keep getting this error when plotting intensities vs betas. sdf is a large list of 36 different sdfs. Each one of those has a data frame of  7 columns (probe_ID, MG, MR, UG, UR, col, mask) and 296,070 rows. I am stuck and not sure what the error means. I think I need to somehow get the code to realize those columns are within each one of the 36 sdfs but I am unsure how to do such a thing... 

sdf<-openSesame("~/mousetox/idats",func=NULL, prep="TQCDPB",platform="MM285") #returns list of 36 prepped sdfs

> sesameQC_plotIntensVsBetas(sdf)
Error in totalIntensities(sdf, mask = mask) : 
  all(c("MG", "UG", "MR", "UR") %in% colnames(sdf)) is not TRUE

Any tips would be appreciated!

**Comment by zwdzwd** [comment]
I think this function takes one element from the list. So try sesameQC_plotIntensVsBetas(sdfs[[1]])
It will be difficult to overlay multiple heatmaps on top of each other.

**Comment by ardan33** [comment]
This worked - thank you!
