### ISSUE TITLE
Error with sesameDataCache()

### ISSUE THREAD

**Issue by ardan33** [zwdzwd/sesame#126]
I previously ran sesame no problem with version 3.17. However, since updating to version 3.18, I am having issues with the sesameDataCache() function.

This is the code I ran:
`if (!require("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install(version="3.18")
BiocManager::install("sesame", force=TRUE)
BiocManager::install("sesameData", force=TRUE)

BiocManager::install("ExperimentHub", force=TRUE)
BiocManager::install("BiocFileCache", force=TRUE)
getwd()
sessionInfo()
library(sesame)
sesame_checkVersion()
library(sesameData)
sesameDataCache()

This is the error message when I run the last 3 lines :
sesame_checkVersion()
SeSAMe requires matched versions of R, sesame, sesameData and ExperimentHub.
Here is the current versions installed:
R: 4.3.1
Bioconductor: 3.18
sesame: 1.20.0
sesameData: 1.20.0
ExperimentHub: 2.10.0

library(sesameData)
sesameDataCache()
Metadata (N=91):

ExperimentHub Caching fails:
error in evaluating the argument 'x' in selecting a method for function 'query': Failed to collect lazy table.
Caused by error in db_collect():
! Arguments in ... must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?

I have no idea how to fix this... as I am extremely new to R. Any help would be appreciated.

**Comment by seq101** [comment]
@zwdzwd sesameDataCache() seems to be a trending issue!

**Comment by zwdzwd** [comment]
I am not sure. I just deleted my `~/Library/Caches/org.R-project.R/R/ExperimentHub/` and rerun `sesameDataCache()` again on my mac with the following version (which is the closest I can find to the post above) and it seems to work fine. Not sure if it's specific to Windows?
```
R: 4.3.2
Bioconductor: 3.18
sesame: 1.20.0
sesameData: 1.20.0
ExperimentHub: 2.10.0
```

**Comment by ardan33** [comment]
I got this fixed a while ago. I don't remember how I fixed it now, but it seems to be working fine now!
