### ISSUE TITLE
openSesame() returned beta table with NA

### ISSUE THREAD

**Issue by alanlamsiu** [zwdzwd/sesame#139]
Hi @zwdzwd,

I used `openSesame("../idat/")` to open a set of sample generated by the EPIC platform. However, out of the 865,918 non control probes, there were 225,939 probes having "NAs" in at least one sample. But when using GenomeStudio to read the same set of idat files, beta values were called for all probes in all samples. The same happened for data generated by the EPICv2 platform, where 95,488 out of 930,659 non control probes having "NAs" in at least one sample. Are there any reasons why "NAs" were produced here?

For EPIC, I didn't specify any manifest file, while for EPICv2, I used EPICv2.hg38.manifest.tsv.gz.

Thanks.

**Comment by zwdzwd** [comment]
In version 1.18+, sesame doesn't require explicit manifest input for EPICv2. NA were likely produced due to low detection p-value. You can pass `mask=FALSE` to `openSesame(..., mask=FALSE)` to turn off NA-masking.

**Comment by alanlamsiu** [comment]
Thanks @zwdzwd!
