### ISSUE TITLE
Error installing sesameData

### ISSUE THREAD

**Issue by potkat** [zwdzwd/sesame#15]
Hi, 

I got the following error while trying to install sesame. I tried it on different computers and still ended up with the same error. 
I downloaded R4.0 and then tried installing sesame following instructions at https://bioconductor.org/packages/devel/bioc/html/sesame.html

* installing *source* package 'sesameData' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for 'BiocFileCache' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/apottekat/Documents/R/win-library/4.0/Rcpp/libs/x64/Rcpp.dll':
  LoadLibrary failure:  The specified procedure could not be found.

Error: package 'BiocFileCache' could not be loaded
In addition: Warning message:
package 'dbplyr' was built under R version 4.0.2 
Execution halted
ERROR: lazy loading failed for package 'sesameData'
* removing 'C:/Users/apottekat/Documents/R/win-library/4.0/sesameData'

Any help would be appreciated. 

Thanks 
Anita

**Comment by zwdzwd** [comment]
I think this should've been solved with version 1.8+. One needs to run sesameDataCacheAll() the first time sesame is installed.
