### ISSUE TITLE
Is sesame modeling beta or log(beta/(1-beta))?

### ISSUE THREAD

**Issue by alanlamsiu** [zwdzwd/sesame#150]
Hi @zwdzwd,

I remember seeing the details of how sesame models beta using covariates before but I couldn't find the related information recently. I am trying to understand whether sesame is doing `beta ~ beta0 + beta1 x covariate1` or `log(beta/(1-beta)) ~ beta0 + beta1 x covariate1`, assuming only covariate1 is the only covariate.

Thanks.

**Comment by zwdzwd** [comment]
just beta, the default modeling doesn't use M -value. I think one could transform manually if needed.
