### ISSUE TITLE
openSesame func = NULL issue

### ISSUE THREAD

**Issue by JBinkowski** [zwdzwd/sesame#155]
Dear All,
I am currently using sesame (version 1.12.9) to extract beta-values and raw intensities. In the idats/ directory, I have two matched idat files.

Following the documentation, I execute the following commands:

```
betas = openSesame(idat_dir, func = getBetas) # getBetas is the default
sdfs = openSesame(idat_dir, func = NULL) # return SigDF list

print(identical(betas, sdfs))
TRUE
```

The first function call works as expected, however, the second one (mistakenly?) returns beta values instead of the expected list of SigDF objects.

**Comment by zwdzwd** [comment]
thanks for bringing to our attention. Can you update to a more recent version and see if this problem still exists?
