### ISSUE TITLE
Typo in mLiftOver biorxiv paper about needed SeSAMe version

### ISSUE THREAD

**Issue by jdreyf** [zwdzwd/sesame#156]
I think there's a typo in your mLiftOver biorxiv paper, as it states "mLiftOver is implemented R and available in the Bioconductor package SeSAMe (version **3**.21.13+)" but I think you mean 1.21.13+.

**Comment by zwdzwd** [comment]
Thanks for bringing this to our attention. We will fix. Thanks again!
