### ISSUE TITLE
Documentation on what the different listAvailableMasks("EPICv2") are (& how they are derived + recommended use)

### ISSUE THREAD

**Issue by KC-UK** [zwdzwd/sesame#160]
Hi, please could you provide documentation on how the various masks available for EPICv2 are derived and what the recommended use is (especially for dropping loci with SNPs)? 
```
listAvailableMasks("EPICv2")
'M_1baseSwitchSNP_AFR_1pt''M_1baseSwitchSNP_AMR_1pt''M_1baseSwitchSNP_EAS_1pt''M_1baseSwitchSNP_EUR_1pt''M_1baseSwitchSNP_SAS_1pt''M_1baseSwitchSNPcommon_1pt''M_1baseSwitchSNPcommon_5pt''M_2extBase_SNP_AFR_1pt''M_2extBase_SNP_AMR_1pt''M_2extBase_SNP_EAS_1pt''M_2extBase_SNP_EUR_1pt''M_2extBase_SNP_SAS_1pt''M_2extBase_SNPcommon_1pt''M_2extBase_SNPcommon_5pt''M_mapping''M_nonuniq''M_SNP_AFR_1pt''M_SNP_AMR_1pt''M_SNP_EAS_1pt''M_SNP_EUR_1pt''M_SNP_SAS_1pt''M_SNPcommon_1pt''M_SNPcommon_5pt'
```
This is what I see available but I am unclear what they are and what would be the best choice to mask, my data combines two populations from two quite distinct European ancestries.

**Comment by zwdzwd** [comment]
Does this https://zwdzwd.github.io/InfiniumAnnotation/mask2.html have any useful information to you?

**Comment by KC-UK** [comment]
Yes it does, thank you! So would you recommend to use all three common masks (M_mapping+M_nonuniq+M_uncorr_titration) as default? & then for the various SNP masks I can deicide how stringent I want to be?

**Comment by KC-UK** [comment]
Sorry I have another question about how these are applied individually as when I follow this documentation from [here](https://zhou-lab.github.io/sesame/dev/supplemental.html#Preprocessing_Functions) 
`sdf_masked = qualityMask(sdf, "low_mapq")`
e.g. `sdf_masked = qualityMask(sdfs[[1]], "M_SNPcommon_5pt")`
Any listed option provided in the quotes give 32,896 mask==TRUE

**Comment by zwdzwd** [comment]
> Yes it does, thank you! So would you recommend to use all three common masks (M_mapping+M_nonuniq+M_uncorr_titration) as default? & then for the various SNP masks I can deicide how stringent I want to be?

Currently the default mask doesn't include uncorr_titation (I haven't updated but should. the previous verison doesn't contain the titrations). But it makes sense to be cautious about these probes.

**Comment by zwdzwd** [comment]
> Sorry I have another question about how these are applied individually as when I follow this documentation from [here](https://zhou-lab.github.io/sesame/dev/supplemental.html#Preprocessing_Functions) `sdf_masked = qualityMask(sdf, "low_mapq")` e.g. `sdf_masked = qualityMask(sdfs[[1]], "M_SNPcommon_5pt")` Any listed option provided in the quotes give 32,896 mask==TRUE

Do you mean the mask result is the same regardless of the option to qualityMask? Did you provide a sdf already masked?

**Comment by KC-UK** [comment]
Yes exactly, no, all probes are mask == FALSE for this sdf before running the above

**Comment by zwdzwd** [comment]
Thanks for bringing this issue to our attention. It is a bug caused by `...` being overrided by a recently added option (verbose). The uploaded commit should've fixed this. the commit will be incoporated in the next sesame release. 

Thanks again

```R
> sdf = sesameDataGet("EPICv2.8.SigDF")[["GM12878_206909630042_R08C01"]]
> sum(sdf$mask)
[1] 0
> sdf_masked = qualityMask(sdf)
> sum(sdf_masked$mask)
[1] 32896
> sdf_masked = qualityMask(sdf, "recommended") # same as above
> sum(sdf_masked$mask)
[1] 32896
> sdf_masked = qualityMask(sdf, c("recommended", "M_SNPcommon_1pt"))
> sum(sdf_masked$mask)
[1] 36863
> sdf_masked = qualityMask(sdf, "M_SNPcommon_1pt")
> sum(sdf_masked$mask)
[1] 9786
> listAvailableMasks("EPICv2")
 [1] "M_1baseSwitchSNP_AFR_1pt"   "M_1baseSwitchSNP_AMR_1pt"
 [3] "M_1baseSwitchSNP_EAS_1pt"   "M_1baseSwitchSNP_EUR_1pt"
 [5] "M_1baseSwitchSNP_SAS_1pt"   "M_1baseSwitchSNPcommon_1pt"
 [7] "M_1baseSwitchSNPcommon_5pt" "M_2extBase_SNP_AFR_1pt"
 [9] "M_2extBase_SNP_AMR_1pt"     "M_2extBase_SNP_EAS_1pt"
[11] "M_2extBase_SNP_EUR_1pt"     "M_2extBase_SNP_SAS_1pt"
[13] "M_2extBase_SNPcommon_1pt"   "M_2extBase_SNPcommon_5pt"
[15] "M_mapping"                  "M_nonuniq"
[17] "M_SNP_AFR_1pt"              "M_SNP_AMR_1pt"
[19] "M_SNP_EAS_1pt"              "M_SNP_EUR_1pt"
[21] "M_SNP_SAS_1pt"              "M_SNPcommon_1pt"
[23] "M_SNPcommon_5pt"
> recommendedMaskNames()[["EPICv2"]]
[1] "M_1baseSwitchSNPcommon_5pt" "M_2extBase_SNPcommon_5pt"
[3] "M_mapping"                  "M_nonuniq"
[5] "M_SNPcommon_5pt"
> sesame_checkVersion()
SeSAMe requires matched versions of R, sesame, sesameData and ExperimentHub.
Here is the current versions installed:
R: 4.4.0
Bioconductor: 3.19
sesame: 1.21.15
sesameData: 1.21.10
ExperimentHub: 2.11.3
```

**Comment by KC-UK** [comment]
Thanks for this, that definitely helps clarify / explain things for me, best, KC
