### ISSUE TITLE
Error importing illumina mouse methylation array idat files

### ISSUE THREAD

**Issue by OluwayioseOA** [zwdzwd/sesame#17]
Hey. I'm having trouble importing illumina mouse methylation Idat files using openSesame function (openSesame(idat_dir, 'custom_array_name', manifest_file)). I keep getting the error ("Unknown or uninitialised column: `col`") despite downloading the new mouse manifest directly from the illumina website. I wonder if any modification is needed for the manifest to work.

**Comment by DavidTSLin** [comment]
Hi, did you solve this? I would imagine you need to make a custom manifest by pulling and renaming the relevant columns as shown in the vignette; ie.   

Probe_ID          M        U col
  <chr>         <dbl>    <dbl> <chr>
1 cg14361672  7743487 51800947 R
2 cg21784030       NA 29783926 NA
3 cg13417420 27786954  5613976 G

I have run into an issue along this line so I am going to piggy-back on this thread....also doing mouse arrays, however, it seems that following the format suggested in the vignette, it refuses to read the methylation values for Type II probes. If I leave the color as blank, it ignores those probes entirely; if I fill them in as anything else (NA, G, or R), it reads the Type II probes but calculates their betas as NAs. Any advice welcome, thanks!

**Comment by zwdzwd** [comment]
Do you still get this issue with the updated 1.9+ versions?

**Comment by zwdzwd** [comment]
I think this should've been fixed. Let me know if this recurs with the new versions.
