### ISSUE TITLE
sesameDataCache() optimization

### ISSUE THREAD

**Issue by JBinkowski** [zwdzwd/sesame#173]
Hi,

I am building a containerized Django application that uses Sesame as one of its components. Currently, building images for Python dependencies takes approximately 2-3 minutes. Unfortunately, when incorporating the R environment, the build time increases 30x.

I understand that reducing the installation time for R dependencies might be difficult. However, maybe do you have any recommendations on how to improve Sesame data caching during `sesameDataCache()`?

Best

**Comment by zwdzwd** [comment]
Yeah, that was a prior issue with ExperimentHub not compatible with parallel processing. But I thought you only need to run sesameDataCache() once in your container? We just made most function to only require a small subset of the data the function needs in the current 1.23 versions. Not sure that would address the issue though.

**Comment by JBinkowski** [comment]
>  I thought you only need to run sesameDataCache() once in your container`

Yes, just once, but from the perspective of prototyping and debugging long-time building containers are really problematic.

>  We just made most function to only require a small subset of the data the function needs in the current 1.23 versions. Not sure that would address the issue though.

Yes, it's nice improvement! 

Additionally, do you think that is it doable to download `DataCache` prior to building and then simply copy it into the container?

**Comment by zwdzwd** [comment]
Not sure but ExperimentHub seemed to mention that if one just move the files to default location, they should work as if they were downloaded https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/ExperimentHub.html#default-caching-location-update

**Comment by JBinkowski** [comment]
Ok, thank you for support
