### ISSUE TITLE
Error in .sesameDataGet

### ISSUE THREAD

**Issue by anna-miu** [zwdzwd/sesame#19]
Hi,
I tried to read idat files using sesame but experienced the same error. 
> sset <- sesameDataGet('EPIC.1.LNCaP')$sset
Error in .sesameDataGet(title, dateAdded = dateAdded) :
  EPIC.1.LNCaP|2020-08-24 doesn't exist. Try: sesameDataCacheAll("2020-08-24")
> ssets <- lapply(
+     searchIDATprefixes(system.file("extdata/", package = "sesameData")),
+     readIDATpair)
Error in .sesameDataGet(title, dateAdded = dateAdded) :
  HM27.address|2020-08-24 doesn't exist. Try: sesameDataCacheAll("2020-08-24")
Can anyone help me fix? Is there workarounds to handle this?

Thanks very much.

Anna

**Comment by anishbhaswanth** [comment]
I received the same error as well.
```
> ssets <- lapply(
+   searchIDATprefixes("../Data/204339300019/"),
+   readIDATpair)
Error in .sesameDataGet(title, dateAdded = dateAdded) : 
  idatSignature|2018-09-19 doesn't exist. Try: sesameDataCacheAll("2018-09-19")
```
I tried adding the following looking at the previous issues reported here as well:
```
BiocManager::install("ExperimentHub")
```
I still get the same error

**Comment by zwdzwd** [comment]
I think this is an ExperimentalHub issue. Do you still get the issue with the most updated 1.9+ versions? some sessionInfo would be helpful for me. Thanks

**Comment by zwdzwd** [comment]
I think this should've been fixed with the ExperimentHub update and sesameData update.
