### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by schmic05** [zwdzwd/sesame#39]
Dear sesame developers,

We are using sesame as part of our RnBeads (https://rnbeads.org/) package. In the previous versions of the package, such as the one available in the Bioconductor release, there was the ```SigSet``` object available. However, I noted that it is now not available anymore. Can you provide some kind of backwards compatibility as to use the old ```SigSet``` container or to we have to change our code? If yes, what is the new equivalent to the ```SigSet``` container?

Thanks,

Michael

**Comment by zwdzwd** [comment]
Hi Michael,
SigSet is still maintained in the RELEASE_3_13 branch (1.10+). The new class is called SigDF. It lives on master (1.11+). It is still being developed. The hope is that it provides more flexibility to color channel designation and plain texts IO. The documentation of this has just been updated to reflect this
https://bioconductor.org/packages/devel/bioc/vignettes/sesame/inst/doc/sesame.html#The_SigDF_Class
We have a sesame:::SigSetToSigDF function that provides some backward compatibility.  Hope this clarifies.

Wanding

**Comment by schmic05** [comment]
Thanks for the information, but this means that we will have to change our code at least to some extent, since we use the SigSet object internally. I was also wondering how the conversion function helps, since an object of type ```SigSet``` cannot exist anymore (since you deleted the class). We are using the ```SigSet``` constructor in our code, so it would be great if there is some 'legacy' function with the same name that now returns an SigDF object instead of a SigSet. Are all the functions operating on SigSet also applicable to an object of type SigDF?

**Comment by zwdzwd** [comment]
Yes, almost every function name is identical. I don't think you need to change anything if you only use the sesame interface. But the good news is the new SigDF is very transparent and simple. It is not even an S4 class, just a data.frame with five, six columns (and the SigDF string in attr("class")). So if you modifies the SigSet internals, you should find SigDF much easier to work with. The plan is to keep it really simple so someone with the basic knowledge of R data.frame can see the internals and change things.

**Comment by schmic05** [comment]
Alright, thanks for the update. I'll let you know in case we are facing any issues with the new version of the package.
