### ISSUE TITLE
error when trying to run DML with mm285 data

### ISSUE THREAD

**Issue by Riptides** [zwdzwd/sesame#42]
We are currently trying to use the MM285 chip to analyze some rat samples. We realize that most probes will be useless, but ~36k are conserved. Unfortunately we are encountering the following error when trying to run DML.

```
> new_betas <- openSesame(".")
> sample_metadata <- read.table("samples_metadata.txt", header=TRUE, sep="\t", row.names=1)
> probes_to_keep <- read.table("probes_to_keep.txt")
> new_betas_filtered <- subset(new_betas, rownames(new_betas) %in% probes_to_keep$V1)
> dmls <- DML(new_betas_filtered, ~type, meta=sample_metadata)
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
```

There are some NAs in the beta matrix, but most of the 36k conserved probes have beta values. I've read through all the documentation pertaining to MM285 and past issues on github that mention the chip, but I can't seem to figure this out; apologies if I missed something. Any assistance is greatly appreciated.

**Comment by Pancreas-Pratik** [comment]
Thank you very much for this incredible package @zwdzwd! You made a challenging situation of analyzing the relatively new Infinium Mouse Methylation BeadChip Array manageable.

I have also found some NAs in the beta matrix from the dataset I am analyzing. It is interesting because someone previously processed our raw IDAT files through an earlier version of sesame (1.9.9) using the `openSesame()` pipeline function and they did not have NAs in the beta value matrix. Could there be an added step in previous pipeline in sesame 1.9.9 to the current version?

Thank you very much again.
-Pratik

**Comment by zwdzwd** [comment]
> We are currently trying to use the MM285 chip to analyze some rat samples. We realize that most probes will be useless, but ~36k are conserved. Unfortunately we are encountering the following error when trying to run DML.
> 
> ```
> > new_betas <- openSesame(".")
> > sample_metadata <- read.table("samples_metadata.txt", header=TRUE, sep="\t", row.names=1)
> > probes_to_keep <- read.table("probes_to_keep.txt")
> > new_betas_filtered <- subset(new_betas, rownames(new_betas) %in% probes_to_keep$V1)
> > dmls <- DML(new_betas_filtered, ~type, meta=sample_metadata)
> Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
>   0 (non-NA) cases
> ```
> 

Looks like you might be testing probes with NA for an entire level. What if you filter the probes/rows with complete.cases or checkLevels first? (see "Modeling" https://bioconductor.org/packages/devel/bioc/vignettes/sesame/inst/doc/modeling.html)

**Comment by zwdzwd** [comment]
Thank you for the encouraging words. With the new version you can turn off NA masking with mask=FALSE in getBetas. See "SeSAMe Basic Usage" https://bioconductor.org/packages/devel/bioc/vignettes/sesame/inst/doc/sesame.html#NA-Masking for some details. OpenSesame is meant to be used as a default, where we do recommend masking probes based on detection p value and mapping uniqueness. Hope this clarifies

**Comment by Pancreas-Pratik** [comment]
> Thank you for the encouraging words. With the new version you can turn off NA masking with mask=FALSE in getBetas. See "SeSAMe Basic Usage" https://bioconductor.org/packages/devel/bioc/vignettes/sesame/inst/doc/sesame.html#NA-Masking for some details. OpenSesame is meant to be used as a default, where we do recommend masking probes based on detection p value and mapping uniqueness. Hope this clarifies

Thank you again @zwdzwd. I know this is leaning away from an issue and more so towards help with sort-of analysis.

> What if you filter the probes/rows with complete.cases or checkLevels first? 

Do you simply recommend running the `openSesame()` pipeline function followed by `complete.cases` to filter out NAs as a sort-of default, recommended way to proceed with generating a full beta value matrix with no NAs to use for further DMR analysis?

**Comment by zwdzwd** [comment]
`complete.cases` is probably too aggressive since it filtered probes if there is at least one NA from any sample. For DMR analysis, we actually only require at least one non-NA for the level to compare in each contrast variable. We have `checkLevels` function for this.

**Comment by Riptides** [comment]
> > We are currently trying to use the MM285 chip to analyze some rat samples. We realize that most probes will be useless, but ~36k are conserved. Unfortunately we are encountering the following error when trying to run DML.
> > ```
> > > new_betas <- openSesame(".")
> > > sample_metadata <- read.table("samples_metadata.txt", header=TRUE, sep="\t", row.names=1)
> > > probes_to_keep <- read.table("probes_to_keep.txt")
> > > new_betas_filtered <- subset(new_betas, rownames(new_betas) %in% probes_to_keep$V1)
> > > dmls <- DML(new_betas_filtered, ~type, meta=sample_metadata)
> > Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
> >   0 (non-NA) cases
> > ```
> 
> Looks like you might be testing probes with NA for an entire level. What if you filter the probes/rows with complete.cases or checkLevels first? (see "Modeling" https://bioconductor.org/packages/devel/bioc/vignettes/sesame/inst/doc/modeling.html)

This was the problem exactly, apologies for missing that step and thank you for the guidance.
