### ISSUE TITLE
How are probe IDs, CpG Loci, and segment regions generated from DMR related to one another?

### ISSUE THREAD

**Issue by Pancreas-Pratik** [zwdzwd/sesame#43]
Thank you for the sesame package and the InfiniumAnnotation @zwdzwd! Again, I don't know how I would have begun to analyze these new mouse methylation datasets without your incredible efforts!

We have generated DMRs and made heatmaps, however we are confused on the probe IDs, their respective CpG loci, and how these are connected to regions generated after DMR table generation.

I see that the MM285 manifest file has each probe corresponding to a two base CpG locus:
![Screen Shot 2021-07-28 at 11 13 13 PM](https://user-images.githubusercontent.com/71743538/127425870-d098bc39-6212-4910-8f1d-4f98617dc22f.png)
chr12: 103694655 to 103694657

However, when DMRs are generated we have regions, rather than two bases (for the same probe):
![Screen Shot 2021-07-28 at 11 09 27 PM](https://user-images.githubusercontent.com/71743538/127425794-41ee0cff-32bc-430b-9e70-6857a4b49560.png)
chr12: 103694463 to 103695197

I looked at the code and tried to understand and I can see it has something to do with maybe the `dmr_merge_cpgs` function and `GenomicRanges`, just not sure what exactly is happening.

When you get a chance, could you help me understand this, please?

Thank you again : )

**Comment by zwdzwd** [comment]
Sesame test DML first then merge the CpGs into regions. If you just run DML function, you should get just one region. As you have guessed the DMR function essentially merge the neighboring CpGs with the same pattern of methylation change into regions (using the dmr_merge_cpgs function). The result still has one row for each CpG but adds the region which the CpG is merged into. In other words, multiple rows may have the same region column. This is to minimize information loss. But one can easily collapse the data frame by focusing on the unique regions. Hope this clarifies a bit.

**Comment by Pancreas-Pratik** [comment]
Thank you very much @zwdzwd! I appreciate you responding so promptly as well! : )
