### ISSUE TITLE
VisualizeGene() gene coordinates differ from UCSC/GENCODE VM23 and VM25?

### ISSUE THREAD

**Issue by Pancreas-Pratik** [zwdzwd/sesame#45]
Thank you again @zwdzwd for this great package.

 I have been modifying things here and there, I was actually trying to get the transcription start site to show through modifying the `plotTranscripts()` internal function for `VisualizeRegion()`. Eventually I realized the gene coordinates do not match the UCSC/GENCODE VM23 `TxDb.Mmusculus.UCSC.mm10.knownGene` or the UCSC/GENCODE VM25 for some genes.

Here is an example of just the `visualizeGene()` function without any major additions:

`visualizeGene(geneName =  "Isl1", betas = betamatrix, platform="MM285", refversion = "mm10", dwstream = 0, upstream =0)`
![Screen Shot 2021-08-08 at 12 43 48 AM](https://user-images.githubusercontent.com/71743538/128621069-8e1c85f3-aaaa-4c30-821b-ad76f8b89907.png)

The coordinates for Isl1 through sesame are: `chr13:116,298,269-116,309,688`
The coordinates for the closest matching Isl1 transcript on UCSC with VM23 and VM25: `chr13:116,298,281-116,309,689`

You can see, they do not match with the coordinates on the UCSC genome browser or the `TxDb.Mmusculus.UCSC.mm10.knownGene` package, which uses VM23.

(Below `TxDb.Mmusculus.UCSC.mm10.knownGene` selected for Isl1 gene (gene ID: 16392))
![Screen Shot 2021-08-08 at 12 51 10 AM](https://user-images.githubusercontent.com/71743538/128621179-14b65228-09f6-466b-8fea-7cdbf51d4b47.png)

I think this coordinate mismatch could be something going on with `genomeInfo.mm10`, I realize that this is the database that all of the `visualize...()` functions extract information from.

This problem is not only with the Isl1 gene, but also some genes that I am interested in. I just chose Isl1 as a reproducible example. Some of the coordinates for genes are almost perfect, if not already perfect (ie. matching with the UCSC gene coordinates), however many of them do not match for some reason.

Thank you in advance, and I really do look forward to your response!

**Comment by zwdzwd** [comment]
Thanks for the feedback. Looks like this is a difference between the GENCODE gene model and the RefSeq model. Could you help me check if the coordinates match RefSeq? I am happy to update this to GENCODE since that seems to be more used nowadays.

**Comment by Pancreas-Pratik** [comment]
No problem @zwdzwd! You are right! I just checked - the coordinates are a much closer match to RefSeq: 
RefSeq coordinates are: `chr13:116,298,270-116,309,688`

![Screen Shot 2021-08-08 at 9 40 56 PM](https://user-images.githubusercontent.com/71743538/128652988-fac30e35-5fb2-4e97-871f-031e731e0034.png)

It would be awesome if you could update to GENCODE. I am not sure if this would be possible but if you could do VM25 that would be awesome. Another question, if you are to use GENCODE VM25 how will you choose between the different transcripts? Will you just choose the transcript with the largest width? For example, these are the transcripts for Isl1 for VM23, I think there are the same number of different transcripts for VM25:

![128621179-14b65228-09f6-466b-8fea-7cdbf51d4b47](https://user-images.githubusercontent.com/71743538/128653986-51ad52ed-b25d-4ef0-b62e-62931af4ceea.png)

Also a side note:
-------------------
I am currently using your manifest file here:
http://zhouserver.research.chop.edu/InfiniumAnnotation/current/MM285/MM285.mm10.manifest.gencode.vM25.tsv.gz

I added CpG Island, Shore, and Shelf annotations, converted probes to genomic coordinates, and combined that with other resources such as UCSC enhancer/promoter annotations to generate heatmaps that look like this:

![heatmap](https://user-images.githubusercontent.com/71743538/128653432-e719dc0c-a425-4fff-a9ac-fa3f4e3d56e6.png)

Once the genomic coordinates match up, I will be good to go! I would be happy to contribute these codes if you would like? I would just have to neaten them up? I'm pretty sure you have figured out how to do everything I did by just looking at my heatmap 🥇

**Comment by zwdzwd** [comment]
Sure. I will try to update to VM25 this week. 

Re transcript choice: Yes, I usually plot all transcripts. 

Contribution to code: that would be great! What you added will be very helpful. 

Thanks again for all the feedback!

**Comment by Pancreas-Pratik** [comment]
Hi @zwdzwd,

I will try and do the conversion from the RefSeq gene model to GENCODE vM27 (not vM25) gene model myself. It will be a good challenge!

Sincerely,
Pratik

**Comment by Pancreas-Pratik** [comment]
@SteffanChristiansen I have been trying to update to vM27 (mm39) linked here: https://github.com/zwdzwd/sesameData/issues/8 and https://github.com/zwdzwd/sesame/issues/47#issuecomment-922540841, however @zwdzwd must be busy. You may be able to do your analysis using vM25 by recreating the genomeInfo.mm10 with vM25 using the code in https://github.com/zwdzwd/sesameData/issues/8#issuecomment-922540620 You may have to change which ENSEMBL release you download from that script.

**Comment by zwdzwd** [comment]
Sorry about the late response. So far the genomeInfo.mm10 is hosted on our own backup website and will be on Bioconductor in the next release. That's why sesameDataList is missing that. But you can get that from 
https://zhouserver.research.chop.edu/sesameData/genomeInfo.mm10.rda

**Comment by SteffanChristiansen** [comment]
Thanks a lot for your suggestions. 

The `genomeInfo.mm10.rda` looks somewhat truncated with information of only 27578 probes in contrast to the information of 288658 probes for the `MM285.probeInfo.rda`. Additionally, some of the probes are annotated to chr20, chr21, and chr22, which are not a part of mm10. Could it be a mislabeled object?
