### ISSUE TITLE
How to obtain strand information for MM285.mm39.manifest?

### ISSUE THREAD

**Issue by Pancreas-Pratik** [zwdzwd/sesame#47]
Hello @zwdzwd,

I am attempting to update the analysis I am working on from mm10 to mm39, as I found some challenges in finding a database for precise annotations for regulatory features (promoters and enhancers). I, fortunately, found [Ensembl's database file](http://ftp.ensembl.org/pub/current_regulation/mus_musculus/mus_musculus.GRCm39.Regulatory_Build.regulatory_features.20201021.gff.gz) which has these regulatory features annotated for mm39. These annotations were much more clear compared to the previous ones I was using.

I also found that UCSC has CpG Island annotations that are downloadable [here](https://hgdownload.soe.ucsc.edu/goldenPath/mm39/database/cpgIslandExt.txt.gz) for mm39 that I am planning to use as well.

With all that being said, I am troubled with trying to create a very precise `GenomicRanges` object for mm39 using the MM285.mm39.manifest.tsv (obtained from [here](http://zhouserver.research.chop.edu/InfiniumAnnotation/current/MM285/MM285.mm39.manifest.tsv.gz)) that is comparable to the manifest file obtained from `sesameData::sesameDataGet("MM285.mm10.manifest")`. I found that MM285.mm39.manifest.tsv is missing strand information. 

I tried using the strand information from `sesameDataGet("MM285.probeInfo")` However there was only strand information for 9873 probes based on merging by `"CpG_chrm", "CpG_beg", "CpG_end", "probeID"`

**Is there any way you could provide strand information, please?**

Also just a side tid-bit question, **Do you think doing the conversion from mm10 to mm39 in the analysis is a good idea?** I believe the probes within the Illumina Mouse Methylation BeadChip were made using sequences from mm10, therefore by converting the analysis to mm39 there might be some CpG sites that do not align perfectly with some genes as they were originally designed to? Perhaps this would be a good sacrifice as the true (or more true) CpG annotation would be uncovered?

I am also going to attempt to do the conversion from the RefSeq gene model over to the GENCODE vM27 gene model. I plan to submit these contributions, in conjunction with the things I have done [here](https://github.com/zwdzwd/sesame/issues/45#issuecomment-894911269) (just have to finish the project I am working on, then I will gladly submit): 

Thank you in advance. I am really looking forward to your response sir!

-Pratik

**Comment by zwdzwd** [comment]
Hi Pratik,
I think `sesameDataGet("MM285.probeInfo")` is based on mm10. I have yet generated a GenomicRanges object for mm39 yet. But for now you can get the strand information from `MM285.mm39.manifest.tsv` file like you did. The mapFlag column I think is what you need. Since most design is targeting the parent/converted strand, 0 will mean + and 16 will mean -. I am struggling to find time to finalize the mm39 GenomicRanges object in sesame. I should do that. But hope this helps a bit for now.

Wanding

**Comment by Pancreas-Pratik** [comment]
Thank you very much sir!

Sincerely,
Pratik

**Comment by zwdzwd** [comment]
My sense is that if some probes were designed valid on mm10 and become invalid on mm39, that suggests at least the probes were designed to target the part of the mm10 genome where assembly had been incorrect. Based on my observation, most majority of probes are valid design on both mm10 and mm39. So the difference of genome assembly should be minuscule. Analysis on mm39 won't be a conversion, but rather some re-annotation with additional probe filtering. As mm39 is presumably higher in quality than mm10, the annotation based on the updated assembly should also be better. But that's all in theory. It remains to be found out if it's true in practice. just my two cents.

**Comment by Pancreas-Pratik** [comment]
@zwdzwd, when you get a chance. Could you review https://github.com/zwdzwd/sesameData/issues/8 please?

I am trying to move forward an analysis using the mm39, however am at a roadblock. I just have 3, most likely, simple questions for you.
