### ISSUE TITLE
Bug in DMR function for MM285 array data

### ISSUE THREAD

**Issue by OluwayioseOA** [zwdzwd/sesame#60]
I hope this email finds you well. 

I would like to bring to your attention that there seems to be a bug related to analyzing DMR for MM285 data using the latest (github) Sesame version (1.13.18)).
Here is the error message: **"Merging correlated CpGs ... Error in seq_len(n.cpg - 1) : argument must be coercible to non-negative integer".** Please any assistance with debugging this will be appreciated.
Best,
Oladele

**Comment by zwdzwd** [comment]
Hi Oladele,

Sorry this happened. I am debugging now. meanwhile can you verify the packageVersion of sesameData and ExperimentHub. Sometimes the dependencies don't get probably installed when you install R package directly from github.

Wanding

**Comment by OluwayioseOA** [comment]
Hey Wanding,

SesameData: 1.12.0
ExperimentalHub: 2.2.1

Oladele

**Comment by zwdzwd** [comment]
Yeah, could you try 1.13 for sesameData. Usually the sesameData version and sesame needs be matched, e.g., either both 1.12 or 1.13. When you install from Bioconductor, this gets taken care of in an automatic way. Let me know if this solves your issue.

**Comment by OluwayioseOA** [comment]
Thanks for helping. 
Unfortunately, after installing a more recent of version sesameData (1.13.14), the error persists. 
Oladele

**Comment by zwdzwd** [comment]
OK. I assume the vignette examples run fine but your own data throws this error?

To help me understand better could you verify the rownames(betas) of your input has overlap with `DMGetProbeInfo("MM285", "mm10")` since based on the error, looks like the n.cpg is simply zero or not a number.

**Comment by OluwayioseOA** [comment]
Here is what they look like: 

head(rownames(betas))
"cg36602902" "cg36603287" "cg36603393" "cg36603791" "cg36603848" "cg36604001"

head((rownames(DMGetProbInfo output)))
"cg36602742_TC11" "cg36602743_TC21" "cg36602902_BC11" "cg36603287_TC21" "cg36603393_BC21"
"cg36603791_TC21"

Explanation: During my preprocessing, I used "betas <- openSesame(idat_dir)", resulting in betas with ~297k rows. Then I removed the last 4 strings attached to each probeID (e,g _TC11). I filtered duplicated probes and probes with "NAs" and snps. This resulted in ~267k probes and was used for DML analysis but would not work for DMR.

Follow-up question: Do you suggest not to clip the strings associated with each probeID? What about the NAs (representing low quality probes), and snps probes?

Thanks,
Oladele

**Comment by OluwayioseOA** [comment]
Just to update you, just as you suggested, the DMR function worked when I did not clip the last 4 strings.

Thanks for your prompt responses!!!
Oladele

**Comment by zwdzwd** [comment]
I am glad your problem is solved. 

Re clipping the suffix: I would preserve them for most analysis as without the suffix the cg number is not unique on this array (and probably future arrays). More info can be found at 

https://github.com/zhou-lab/InfiniumAnnotation/blob/main/MM285/202010418_MouseArray_ID_system.md
If you really want to collapse to the cg numbers, you could use the `getBetas(collapseToPfx=TRUE)`. This option let you pick the cg variant that maximizes detection.

Hope this helps,
