### ISSUE TITLE
Error loading in idat files

### ISSUE THREAD

**Issue by wvictor14** [zwdzwd/sesame#7]
Hi,

Running into an error while trying to load in my idat files. I tried with the example, and also am running into an error:

```
sset <- readIDATpair(sub('_Grn.idat','',system.file(
  "extdata", "4207113116_A_Grn.idat", package = "sesameData")))
Error in .sesameDataGet(title, dateAdded = dateAdded) : 
  HM27.address|2018-09-19 doesn't exist. Try: sesameDataCacheAll("2018-09-19")
```

I tried running `sesameDataCacheAll("2018-09-19")` which returnes `TRUE`, but not sure what to do with this information.

My `sessionInfo()`:

> R version 3.5.0 (2018-04-23)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows Server >= 2012 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
> [5] LC_TIME=English_Canada.1252    
> 
> attached base packages:
> [1] parallel  stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] sesame_1.0.0         sesameData_1.0.0     ExperimentHub_1.7.2  AnnotationHub_2.13.1 BiocGenerics_0.26.0 
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.17                  compiler_3.5.0                BiocInstaller_1.30.0          later_0.7.3                  
>  [5] BiocManager_1.30.1            RColorBrewer_1.1-2            tools_3.5.0                   base64_2.0                   
>  [9] digest_0.6.18                 bit_1.1-14                    preprocessCore_1.42.0         RSQLite_2.1.1                
> [13] memoise_1.1.0                 pkgconfig_2.0.1               shiny_1.1.0                   DBI_1.0.0                    
> [17] curl_3.2                      yaml_2.1.19                   httr_1.3.1                    S4Vectors_0.18.3             
> [21] IRanges_2.14.10               stats4_3.5.0                  bit64_0.9-7                   grid_3.5.0                   
> [25] Biobase_2.40.0                R6_2.2.2                      AnnotationDbi_1.42.1          DNAcopy_1.56.0               
> [29] wheatmap_0.1.0                blob_1.1.1                    magrittr_1.5                  promises_1.0.1               
> [33] htmltools_0.3.6               randomForest_4.6-14           colorspace_1.3-2              mime_0.5                     
> [37] interactiveDisplayBase_1.19.0 xtable_1.8-2                  httpuv_1.4.4.1                openssl_1.0.1                
> [41] illuminaio_0.22.0       
> 

I was also wondering if it is possible to convert a `minfi::RGChannelSet` to `sesame:sigset` object as my current pipeline is using `minfi` and it would be convenient to avoid loading in idats twice.

**Comment by zwdzwd** [comment]
Sorry to hear about this issue. Running these code on Mac and Linux seems fine. I will go find a windows machine to test it out. Can you do sesameDataListDates() and sesameDataList() and sesameData:::latest_date?

`sesamize` does takes a minfi::RGChannelSet as input and returns a minfi RGSet so that you can keep your minfi pipeline. I will make it optionally return only the sigset.

Thanks for your feedback

**Comment by wvictor14** [comment]
From the same session:

`sesameDataListDates()`

> snapshotDate(): 2018-04-27
> numeric(0)

`sesameDataList()`
> snapshotDate(): 2018-04-27
> character(0)

`sesameData:::latest_date()`
> Error: attempt to apply non-function

`sesamize()` applies `noob` and  `dyeBiasCorrTypeINorm()` to an `minfi::RGChannelSet`?

**Comment by askw23** [comment]
Hi,
I am also having troubles loading in my IDAT-files (which worked in June when I used Sesame). I am getting a different error message than wvictor14 though:
sset <- lapply(searchIDATprefixes(bdir),readIDATpair)
Error in .local(x, i, j, ...) : 'i' must be length 1
And the same error message when trying the example files:
sset <- lapply(searchIDATprefixes(system.file("extdata/", package = "sesameData")), readIDATpair)
Error in .local(x, i, j, ...) : 'i' must be length 1
sset <- readIDATpair(sub('_Grn.idat','',system.file("extdata", "4207113116_A_Grn.idat", package = "sesameData")))
Error in .local(x, i, j, ...) : 'i' must be length 1

Different error message when trying without the lapply command:
IDATprefixes <- searchIDATprefixes(system.file("extdata/", package = "sesameData"))
readIDATpair(IDATprefixes)
Error in file(file, "rb") : invalid 'description' argument
In addition: Warning messages:
1: In if (!file.exists(file)) { :
  the condition has length > 1 and only the first element will be used
2: In if (grepl("\\.gz", file)) con <- gzfile(file, "rb") else con <- file(file,  :
  the condition has length > 1 and only the first element will be used

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252
[4] LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sesame_0.99.4        sesameData_0.99.4    ExperimentHub_1.7.6  AnnotationHub_2.13.6 BiocGenerics_0.27.1 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18                  compiler_3.5.0                later_0.7.4                   BiocManager_1.30.2           
 [5] RColorBrewer_1.1-2            tools_3.5.0                   base64_2.0                    digest_0.6.16                
 [9] bit_1.1-14                    RSQLite_2.1.1                 memoise_1.1.0                 preprocessCore_1.43.0        
[13] pkgconfig_2.0.2               shiny_1.1.0                   DBI_1.0.0                     curl_3.2                     
[17] yaml_2.2.0                    httr_1.3.1                    S4Vectors_0.19.19             IRanges_2.15.17              
[21] stats4_3.5.0                  bit64_0.9-7                   grid_3.5.0                    Biobase_2.41.2               
[25] R6_2.2.2                      AnnotationDbi_1.43.1          DNAcopy_1.55.0                wheatmap_0.1.0               
[29] blob_1.1.1                    magrittr_1.5                  promises_1.0.1                htmltools_0.3.6              
[33] randomForest_4.6-14           mime_0.5                      interactiveDisplayBase_1.19.2 xtable_1.8-3                 
[37] colorspace_1.3-2              httpuv_1.4.5                  openssl_1.0.2                 illuminaio_0.23.2     

> sesameDataListDates()
Error in sesameDataListDates() : 
  could not find function "sesameDataListDates"

> sesameDataList()
snapshotDate(): 2018-10-30
 [1] "EPIC.1.LNCaP"              "EPIC.5.normal"             "HM450.1.TCGA.PAAD"         "HM450.10.TCGA.PAAD.normal"
 [5] "HM450.10.TCGA.BLCA.normal" "HM450.76.TCGA.matched"     "genomeInfo.hg19"           "genomeInfo.hg38"          
 [9] "EPIC.address"              "HM450.address"             "HM27.address"              "EPIC.hg19.manifest"       
[13] "EPIC.hg38.manifest"        "HM27.hg19.manifest"        "HM27.hg38.manifest"        "HM450.hg19.manifest"      
[17] "HM450.hg38.manifest"       "EPIC.probeInfo"            "HM450.probeInfo"           "HM27.probeInfo"           
[21] "leukocyte.betas"           "ref.methylation"           "age.inference"             "ethnicity.inference"      
[25] "sex.inference"             "EPIC.1.LNCaP"              "EPIC.5.normal"             "HM450.1.TCGA.PAAD"        
[29] "HM450.10.TCGA.PAAD.normal" "HM450.10.TCGA.BLCA.normal" "HM450.76.TCGA.matched"     "genomeInfo.hg19"          
[33] "genomeInfo.hg38"           "EPIC.address"              "HM450.address"             "HM27.address"             
[37] "EPIC.hg19.manifest"        "EPIC.hg38.manifest"        "HM27.hg19.manifest"        "HM27.hg38.manifest"       
[41] "HM450.hg19.manifest"       "HM450.hg38.manifest"       "EPIC.probeInfo"            "HM450.probeInfo"          
[45] "HM27.probeInfo"            "leukocyte.betas"           "ref.methylation"           "age.inference"            
[49] "ethnicity.inference"       "sex.inference"            

> sesameData:::latest_date()
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'latest_date' not found

Would appreciate any help in getting it to work again, thanks!

**Comment by zwdzwd** [comment]
@wvictor14 one possibility is that your ExperimentHub is outdated. Could you update that?
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ExperimentHub", version = "3.8")
```

Let me know how it goes. I will put some version constraints to sesame install.

Thanks,

**Comment by zwdzwd** [comment]
@askw23 Can you also try updating ExperimentHub? It seems ExperimentHub_1.7.7+ works on my end.

Thanks,

**Comment by wvictor14** [comment]
@zwdzwd It's working now! Thanks

I'll leave this issue open for @askw23

**Comment by askw23** [comment]
After updating the ExperimentHub and getting the release version it's working for me as well! Thanks @zwdzwd!

**Comment by zwdzwd** [comment]
You are welcome. Thanks for feedbacks ;) @wvictor14 @askw23

**Comment by yuabrahamliu** [comment]
Hi there, 

I met a similar problem when loading my idat files into R in Linux system.

When I run `readIDATpair('/mypath/201532190133_R07C01')`, it will return the error like, 

`Error in .sesameDataGet(title, dateAdded = dateAdded) :
  EPIC.address|2018-09-19 doesn't exist. Try: sesameDataCacheAll("2018-09-19")
`

While when I run `lapply(IDATprefixes, readIDATpair)`, it will return the error like, 

`Error in FUN(X[[i]], ...) : Grn IDAT does not exist`

But actually all the files are there.

Some information is like this, 
`sesameDataListDates()`
`snapshotDate(): 2018-04-27`

`sesameDataList()`
`snapshotDate(): 2018-04-27`

`sesameData:::latest_date`
`"2018-09-19"`

I don't have much experience on SeSAME, so could anyone give me some suggestions?

Thank you so much!

**Comment by zwdzwd** [comment]
Hi @yuabrahamliu ,
Sorry to see this problem happen again. But did you try updating ExperimentHub? Since it seems you are still getting the old sesameData.

**Comment by yuabrahamliu** [comment]
Yes. I have updated ExperimentHub just now and it seemed works. Thank you
so much!

Wanding Zhou - Bioinformatics <notifications@github.com> 于2019年2月12日周二
下午12:49写道：

**Comment by yuabrahamliu** [comment]
Hi Wanding,

May I ask another question? Is there any way to convert SigSet class to
GenomicRatioSet class using SeSame? Becaue I am going to use the compartmap
package, which requires GenomicRatioSet as input. Thank you so much!

Best,
Yu

刘宇 <yuabrahamliu@gmail.com> 于2019年2月12日周二 下午4:19写道：

**Comment by zwdzwd** [comment]
Hi Yu, 
can you try
```
minfi::RatioSet(Beta = as.matrix(sset), CN = as.matrix(log2(totalIntensities(sset)))
```
see if this works for compartmap

Wanding

**Comment by yuabrahamliu** [comment]
Thank you Wending. I have tried that, but it said S4 object cannot be
converted to matrix, so I used the following to do that,

`grset <- makeGenomicRatioSetFromMatrix(mat = betamatrix, rownames =
rownames(betamatrix),

 pData = pd,

 array = "IlluminaHumanMethylationEPIC",

 annotation = 'ilm10b4.hg19')
`
I think it is fine, but I am not sure. What do you think? Thank you.

Best,
Yu


Wanding Zhou - Bioinformatics <notifications@github.com> 于2019年2月12日周二
下午11:15写道：

**Comment by yuabrahamliu** [comment]
Hi Wanding,

Another question about SeSAME is that, after get the beta values, it is
still necessary to do batch correction, right? Use tools like ComBat.
Because my data are from different batches. I think I need to correct the
batch effect before using compartmap, right? Thank you so much.

Best,
Yu

刘宇 <yuabrahamliu@gmail.com> 于2019年2月13日周三 下午4:50写道：

**Comment by yyshi1** [comment]
Hello, I am having a problem loading idat files too. 
Error in readIDATpair(x, platform = platform, manifest = manifest) :
  Grn IDAT does not exist

We installed R_360 of Anaconda in linux cluster and install seSAMe package. 

Yunling

**Comment by wvictor14** [comment]
Yunling, the error message seems to suggest a particular sample doesn't have a GRN idat. Maybe first check the physical location of the idats and confirm that all RED idats have a paired GRN idat?

**Comment by yyshi1** [comment]
Hi Victor,

To test the package, I put only two idat files: one grn and one red. I also upgrade ExperimentHub to version 1.10.0 and other package recommended by BiocManager. I got same error message: Grn IDAT does not exist

**Comment by zwdzwd** [comment]
Could you post your command to load so that I can test? My hunch is that you were not giving the prefixes of the files. But can be other things.

**Comment by yyshi1** [comment]
You do not need system.file step. I used dir directly in openSeame function and it worked.

**Comment by yyshi1** [comment]
Hi Victor,

library('sesame')
dir = ' /meth/idat/'
idat_dir <- system.file(dir, package = "sesameData")
betas <- openSesame(idat_dir, "EPIC")
 
I also use another method to load the file:
betas <- do.call(cbind, lapply(searchIDATprefixes(idat_dir), function(pfx) {
    pfx %>% readIDATpair %>% pOOBAH %>%
        noob %>% dyeBiasCorrTypeINorm %>% getBetas
}))
 
Error in searchIDATprefixes(idat_dir) : file.exists(dir.name) is not TRUE

check on the directory:
list.files(dir)
[1] "202920680005_R01C01_Grn.idat" "202920680005_R01C01_Red.idat"

bypass idat_dir <- system.file("idat/", package = "sesameData") as following, I was able to load the idat file.
idat_dir = '/meth/idat/'
betas <- openSesame(idat_dir, 'EPIC') 

It appears that system.file(idat_dir, package = "sesameData") does not read return anything.

Although I was able to get following function works, the ssets is a simple list. 
ssets <- lapply(
    searchIDATprefixes(idat_dir),
    readIDATpair)

Best regards,

Yunling

**Comment by yyshi1** [comment]
I posted them and realized I can not bypass system.file step.

**Comment by wvictor14** [comment]
It sounds like you have solved the problem.

What's the output of pfx?

**Comment by yyshi1** [comment]
Hi Vector,

I was able to run the program. The pfx is directory containing idat files. I tried one plate with 96 samples like below and it terminated premature with "Killed" message.  
ssets <- lapply(
    searchIDATprefixes(idat_dir),
    readIDATpair)

I use readIDATpair to process a sample at a time and had similar issue. Sometime, the program is killed at 70ish, the most advance is 95 samples. Because the program posted "Killed", the script with tryCatch does not prevent the script being killed. For the sample was could not processed in iteration process, I can run readIDATpair on this sample and it works. I do not know why? Any idea or suggestion? 

Yunling

**Comment by zwdzwd** [comment]
@HamedY9 curious if this is on Windows? I think it might be because file.exists is not recognizing the directory as a file on Windows. I just uploaded a fix. Can you try install with `BiocManager::install('zwdzwd/sesame') and restart R? see if that solves the problem.

**Comment by HamedY9** [comment]
Thank you so much, you are a life saver :D
Yes I am working on windows and it worked very well. I can't thank you enough!
All the best,
H.

**Comment by HamedY9** [comment]
Hi
I am getting another type of error related to sesameData! 
When I run: 
betas<-openSesame(sdfs, BPPARAM=BiocParallel::MulticoreParam(2))

I receive this error:
Error: BiocParallel errors
  1 remote errors, element index: 1
  95 unevaluated and other errors
  first remote error: could not find function "inferPlatformFromProbeIDs"

I tried to find the solution but I cannot find a proper one! 
It seems there is no inferPlatformFromProbeIDs at all in my system! 
it is worthy to mention that I am using windows system!

**Comment by zwdzwd** [comment]
Sounds like it's due to an older version of sesameData. Can you try `BiocManager::install("zwdzwd/sesameData")`?

**Comment by HamedY9** [comment]
I installed sesameData as you said but still receiving the same error! :(

**Comment by zwdzwd** [comment]
What is the output of your `packageVersion("sesameData")`? Did you restart your R?

**Comment by HamedY9** [comment]
Yes I did restart the R 
And the output is 1.12.0

**Comment by zwdzwd** [comment]
Are you sure 
BiocManager::install("zwdzwd/sesameData")
finishes without issue?

Here is what I got on my end. 
> packageVersion("sesameData")
[1] ‘1.13.33’

**Comment by HamedY9** [comment]
It worked and the version now is 1.13.33! Thanks
However, I was wondering if there is any place to indicate the version needed for this type of analysis. 
I am receiving another error: 
betas<-openSesame(sdfs, BPPARAM=BiocParallel::MulticoreParam(2))
Platform set to: MM285
Error: BiocParallel errors
  1 remote errors, element index: 1
  95 unevaluated and other errors
  first remote error: 
| File KYCG.MM285.mask.20220123 needs to be cached to be used in sesame.
| Please make sure you have updated ExperimentHub and try
| > sesameDataCacheAll()
| to retrieve and cache needed sesame data.

I did sesameDataCacheall() but it didn't work. The ExperimentHub  version is 2.2.1 which is the latest version of this package! 
Interestingly, I did sesameDataCacheall(), and in following it downloaded some data. 
but here is coming other errors:

sesameDataCache("MM285")
Error in sesameDataCache("MM285") : unused argument ("MM285")


sesameDataCacheAll()
snapshotDate(): 2022-03-16
Metadata (N=43):


mft <- sesameDataGet('MM285.mm10.manifest')
Error in .sesameDataGet(title, use_alternative = use_alternative) : 
  Data MM285.mm10.manifest not found.


I am trying to find the solution in the internet but there is few tips about them!

**Comment by zwdzwd** [comment]
I think you need to update the ExperimentHub package to the most latest version on devel branch as well. Please follow this
https://bioconductor.org/packages/devel/bioc/html/ExperimentHub.html
Once the update rolls into the next release (~May), it will be a lot more consistent.

**Comment by rlowe17** [comment]
Hey zwdzwd, hoping you can help! I am on Windows and have tried the advice already in the thread. I have ran BiocManager::install("zwdzwd/sesameData") and restarted R several times, but my packages appear up to date when referencing the Basic Usage doc. However, I am still getting a Grn IDAT does not exist error.

> idat_dir = system.file(dir, package = "sesameData")
> 
> betas = openSesame(idat_dir, BPPARAM = BiocParallel::MulticoreParam(2))
Error in readIDATpair(x, platform = platform, manifest = manifest) : 
  Grn IDAT does not exist

> sapply(c("sesame","sesameData","ExperimentHub"),
+     function(x) as.character(packageVersion(x)))
       sesame    sesameData ExperimentHub 
     "1.15.7"      "1.14.0"       "2.4.0"

**Comment by zwdzwd** [comment]
is `dir` a variable in your example? that's also an R function. Does the following work?

```
idat_dir = system.file("", package = "sesameData")
betas = openSesame(idat_dir, BPPARAM = BiocParallel::MulticoreParam(2))
```

**Comment by rlowe17** [comment]
Thank you so much for such a quick response! 

Yes, dir was a variable. The commands you provided did run and provided the following warning:
> idat_dir = system.file("", package = "sesameData")
> betas = openSesame(idat_dir, BPPARAM = BiocParallel::MulticoreParam(2))
Warning message:
In BiocParallel::MulticoreParam(2) :
  MulticoreParam() not supported on Windows, use SnowParam()

I have tried feeding the path a few different ways:
> dir = "C:/Users/RLowe/Desktop/oneidat"
> idat_dir = system.file(dir, package = "sesameData")
> betas = openSesame(idat_dir, BPPARAM = BiocParallel::MulticoreParam(2))
Error in readIDATpair(x, platform = platform, manifest = manifest) : 
  Grn IDAT does not exist
> dir = "C:\\Users\\RLowe\\Desktop\\oneidat"
> idat_dir = system.file(dir, package = "sesameData")
> betas = openSesame(idat_dir, BPPARAM = BiocParallel::MulticoreParam(2))
Error in readIDATpair(x, platform = platform, manifest = manifest) : 
  Grn IDAT does not exist
> dir = "C:\Users\RLowe\Desktop\oneidat"
Error: '\U' used without hex digits in character string starting ""C:\U"
> idat_dir = system.file("C:\\Users\\RLowe\\Desktop\\oneidat", package = "sesameData")
> betas = openSesame(idat_dir, BPPARAM = BiocParallel::MulticoreParam(2))
Error in readIDATpair(x, platform = platform, manifest = manifest) : 
  Grn IDAT does not exist
> idat_dir = system.file("C:/Users/RLowe/Desktop/oneidat", package = "sesameData")
> betas = openSesame(idat_dir, BPPARAM = BiocParallel::MulticoreParam(2))
Error in readIDATpair(x, platform = platform, manifest = manifest) : 
  Grn IDAT does not exist

I also tried SnowParam, but the Grn IDAT is still being pesky.

**Comment by zwdzwd** [comment]
I think it's a misunderstanding. once you have dir, you don't need `idat_dir = ...`. just do
betas = openSesame(dir)

**Comment by rlowe17** [comment]
Awesome! It looks like that worked. Thank you so much for such quick help!

**Comment by Jmase0921** [comment]
Hey zwdzwd, 

I am on Windows and have tried the advice already in the thread. I am really new to R and SeSame. I am also receiving the error message: 
Error in readIDATpair(x, platform = platform, manifest = manifest) : 
  Grn IDAT does not exist

I have updated my packages and here is my sessioninfo:

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sesame_1.16.1       sesameData_1.17.8   ExperimentHub_2.6.0 AnnotationHub_3.6.0 BiocFileCache_2.6.1
[6] dbplyr_2.3.2        BiocGenerics_0.44.0

loaded via a namespace (and not attached):
 [1] bitops_1.0-7                  matrixStats_0.63.0            bit64_4.0.5                  
 [4] filelock_1.0.2                RColorBrewer_1.1-3            httr_1.4.5                   
 [7] rprojroot_2.0.3               GenomeInfoDb_1.34.9           tools_4.2.1                  
[10] utf8_1.2.3                    R6_2.5.1                      DBI_1.1.3                    
[13] colorspace_2.1-0              withr_2.5.0                   tidyselect_1.2.0             
[16] prettyunits_1.1.1             processx_3.8.0                preprocessCore_1.60.2        
[19] bit_4.0.5                     curl_4.3.3                    compiler_4.2.1               
[22] cli_3.4.1                     Biobase_2.58.0                desc_1.4.2                   
[25] DelayedArray_0.23.2           scales_1.2.1                  readr_2.1.4                  
[28] callr_3.7.3                   rappdirs_0.3.3                stringr_1.5.0                
[31] digest_0.6.31                 XVector_0.38.0                pkgconfig_2.0.3              
[34] htmltools_0.5.5               MatrixGenerics_1.10.0         fastmap_1.1.1                
[37] rlang_1.1.0                   rstudioapi_0.14               RSQLite_2.3.1                
[40] shiny_1.7.4                   generics_0.1.3                wheatmap_0.2.0               
[43] BiocParallel_1.32.6           dplyr_1.1.1                   RCurl_1.98-1.12              
[46] magrittr_2.0.3                GenomeInfoDbData_1.2.9        Matrix_1.5-4                 
[49] Rcpp_1.0.10                   munsell_0.5.0                 S4Vectors_0.36.2             
[52] fansi_1.0.4                   lifecycle_1.0.3               stringi_1.7.12               
[55] yaml_2.3.7                    SummarizedExperiment_1.28.0   zlibbioc_1.44.0              
[58] plyr_1.8.8                    pkgbuild_1.4.0                grid_4.2.1                   
[61] blob_1.2.4                    parallel_4.2.1                promises_1.2.0.1             
[64] crayon_1.5.2                  lattice_0.21-8                Biostrings_2.66.0            
[67] hms_1.1.3                     KEGGREST_1.38.0               ps_1.7.4                     
[70] pillar_1.9.0                  GenomicRanges_1.50.2          reshape2_1.4.4               
[73] codetools_0.2-19              stats4_4.2.1                  glue_1.6.2                   
[76] BiocVersion_3.16.0            remotes_2.4.2                 BiocManager_1.30.20          
[79] png_0.1-8                     vctrs_0.6.1                   tzdb_0.3.0                   
[82] httpuv_1.6.9                  purrr_1.0.1                   gtable_0.3.3                 
[85] cachem_1.0.7                  ggplot2_3.4.2                 mime_0.12                    
[88] xtable_1.8-4                  later_1.3.0                   tibble_3.2.1                 
[91] AnnotationDbi_1.60.2          memoise_2.0.1                 IRanges_2.32.0               
[94] ellipsis_0.3.2                interactiveDisplayBase_1.36.0

However, I am still getting a Grn IDAT does not exist error. May you please help with this matter?

**Comment by OlatunbosunArowolo** [comment]
Hi zwdzwd,

I am having similar issues. Please kindly assist

This is my line of code

betas <- openSesame(idat_dir, "MM285", manifest = temp).

This is the error message am getting

Error: BiocParallel errors
  1 remote errors, element index: 1
  59 unevaluated and other errors
  first remote error:
Error in prepSesame(readIDATpair(x, platform = platform, manifest = manifest), : all(codes %in% cfuns$code) is not TRUE

**Comment by ardan33** [comment]
Hi- I am new to methylation data and using the mouse methylation array (and new-er to R). I have been able to do the following code successfully. I am confused though. What does sdf stand for? And do I need to do quality control before or after I do the betas?  I have been able to do the following code successfully, but I don't know if I need to update the beta values somehow after the data has gone through the QC code? 

dir= "~/mousetox/idats"
betas = openSesame(dir, BPPARAM = BiocParallel::MulticoreParam(2))
sdf<-openSesame("~/mousetox/idats",func=NULL, prep="TQCDPB",platform="MM285") #returns prepped sdfs 
qcs = openSesame(sdf, prep="", func=sesameQC_calcStats) #calculate quality control stats of the sdfs

**Comment by ardan33** [comment]
Hi- I am new to methylation and using the mouse methylation array. I am also new-er to R Studio. I am able to do the following code successfully- but I don't know if I am supposed to find new betas after the qcs code?? In my mind, there will be less beta values after quality control? Or am I interpreting this wrong? Also- when and where does normalization occur? Thanks!

`dir= "~/mousetox/idats"
betas = openSesame(dir, BPPARAM = BiocParallel::MulticoreParam(2))
sdf<-openSesame("~/mousetox/idats",func=NULL, prep="TQCDPB",platform="MM285") #returns prepped sdfs 

qcs = openSesame(sdf, prep="", func=sesameQC_calcStats) #calculate quality control stats of the sdfs
`

**Comment by hamedyasavoli** [comment]
Hi ardan,

Hope you are doing well. 

From what I understand, after the QC process, you'll be able to see the quality of the samples. Don't worry, your betas won't decrease after this. Once you've done the QC, you can easily spot any samples that aren't up to par and then decide if you'd like to remove them. 🙂
Best,
Hamed

**Comment by MSaadfarooq** [comment]
Hi, I just started using SeSAMe and want to know how to perform modeling, inferences, KYCG on my data?? what sort of input is required from my data? In example (zhou-lab.github.io/sesame/dev/modeling.html) only predefined dataset was used. I am working on human EPICv2 array and performed QC steps successfully. Kindly also update all the functions for EPICv2. Thanks in advance!
