### ISSUE TITLE
Error with trying to use mc.cores with the DML() function

### ISSUE THREAD

**Issue by etiennedanis** [zwdzwd/sesame#75]
Dear Dr. Zhou,

Thank you very much for creating Sesame!
It is a fantastic tool.
The DML function works great but when I try to specify the number of cores by using `mc.cores = 4` for example, I get the following error message:

`Error in d$value$value : $ operator is invalid for atomic vectors`

Is there anything I can do to fix this issue?

Thank you very much in advance.
Best,
Etienne

**Comment by etiennedanis** [comment]
It looks like I figured it out.
I just needed to load two libraries: `BiocParallel` and `parallel`.

**Comment by etiennedanis** [comment]
It actually did not work.
I'm now getting the following error:
Error: BiocParallel errors
0 remote errors, element index: 
8714 unevaluated and other errors
first remote error:
5.
stop(.error_bplist(res))
4.
.bpinit(manager = manager, X = X, FUN = FUN, ARGS = ARGS, BPPARAM = BPPARAM, 
BPOPTIONS = BPOPTIONS, BPREDO = BPREDO)
3.
BiocParallel::bplapply(seq_len(nrow(betas)), function(i) {
m0 <- lm(betas[i, ] ~ . + 0, data = as.data.frame(mm))
sm <- summary(lm(betas[i, ] ~ . + 0, data = as.data.frame(mm)))
sm$cov.unscaled <- NULL ...
2.
BiocParallel::bplapply(seq_len(nrow(betas)), function(i) {
m0 <- lm(betas[i, ] ~ . + 0, data = as.data.frame(mm))
sm <- summary(lm(betas[i, ] ~ . + 0, data = as.data.frame(mm)))
sm$cov.unscaled <- NULL ...
1.
DML(se, ~type, mc.cores = 5)

I am going to try the newest version (in development) of BiocParallel.

**Comment by etiennedanis** [comment]
Getting the newest version of BiocParallel (not official yet but still available): 1.31.10 seems to have solved the problem for now.

**Comment by zwdzwd** [comment]
Sorry for the tardy response. We also changed the `mc.cores` argument to `BPPARAM` to allow other options to the BiocParallel in case MulticoreParam doesn't work (Looks like there has been some active development there).  https://github.com/zwdzwd/sesame/blob/c3d5e3b2cad347dfe5de046da36a1814eb51a0f8/R/dm.R#L65
