### ISSUE TITLE
Upgrade breaks code (negative controls)

### ISSUE THREAD

**Issue by notmaurox** [zwdzwd/sesame#80]
Greetings,

I recently updated from sesame 1.12.9 to sesame 1.14.2.

I had some code that loaded a custom manifest and separated out the control dashboard into a dataframe with columns: Address, Type, Color_Channel, Name. In version 1.12.9 this code set up my manifest so that sesame was able to access intensities of the control dashboard. However since updating to 1.14.2, sesame is unable to compute pNegECDF because it doesn't recognize any intensity values for the control dashboard.

Currently the following works to access the control dashboard intensity

> - attr(sset, "control")
                            G     R    col                    type
BS.Conversion.I.U4        123   278  Color  BISULFITE CONVERSION I
BS.Conversion.I.C1        119   258  Color  BISULFITE CONVERSION I
BS.Conversion.I.U1        270   254  Color  BISULFITE CONVERSION I
BS.Conversion.I.C5        112   257  Color  BISULFITE CONVERSION I

but this seems to be the broken function
> - controls(sset)
        Address                    Type                    Name Color_Channel MG MR UG UR
NA     15700381  Bisulfite Conversion I    BS_Conversion_I_54_A         Color NA NA NA NA
NA.1   22795447  Bisulfite Conversion I    BS_Conversion_I_24_B         Color NA NA NA NA
NA.2   24637490  Bisulfite Conversion I    BS_Conversion_I_24_A         Color NA NA NA NA
NA.3   26725400  Bisulfite Conversion I    BS_Conversion_I_55_B         Color NA NA NA NA

Any advice on how to load the control dashboard so that pNegECDF works again would be appreciated.

Thanks,
Mauro

**Comment by notmaurox** [comment]
I think part of the issue is that loading the control dashboard using the legacy format the dataframe is initialized with a column "type"

https://github.com/zwdzwd/sesame/blob/master/R/sesame.R#L341

but then when the negative controls are pulled for pneg it filters on column "Type"

https://github.com/zwdzwd/sesame/blob/master/R/detection.R#L51

I don't see how loading the control dash using the newer chipAddressToSignal method fixes this issue as it doesn't carry over the "type" column that's needed by the negControls()

**Comment by zwdzwd** [comment]
Thanks for the feedback. Previously the control probes were stored separately. In current and future versions, the control probes are included as normal probes in the manifest but with a ctl- prefix in probe id.

These control probes will be retrieved as follows,
https://github.com/zwdzwd/sesame/blob/27587602bbc73795d07995593f1cf27e9da1f231/R/SigDFMethods.R#L121
The "Type" was actually from the manifest annotation files.

Currently, we have a little hybrid solution, as control probe annotation lives outside the address file. I am hoping to unify this without adding another column, maybe in the probe ID after the tango address. 

Are you using 1.4.2 on a previously generated sset? It might not be compatible. I tested the negControls function on my end, it seems to work.

**Comment by notmaurox** [comment]
Hi Wanding - I am on sesame_1.15.9 and am loading a custom array csv and calling readIDATpair after separating out the assays from the control dash (old format). I think my problem is that my custom array does not have a corresponding manifest annotation file. I do have a Type column in the control dashboard section of the manifest. I think a hack in the meantime would be to populate a Type column in the main sset dataframe using the control dashboard

If you have a vignette explaining the updated process for using custom arrays so that sesame is able to find the negative controls I'd appreciate an example.

I am happy to hear about the improvement of control dashboard formatting to be more consistent with the other assays.

**Comment by zwdzwd** [comment]
I updated the code to 1.15.10 where you can get negative probes from probe IDs. I didn't remove the old code of getting control probe annotation for backward compatibility
https://github.com/zwdzwd/sesame/blob/0fb810fbccd3633bd2bf534496a814693f5c5e25/R/detection.R#L50
But in short you can do something like (treating EPIC as a custom array here)
```R
> addr = sesameAnno_buildAddressFile("https://github.com/zhou-lab/InfiniumAnnotationV1/raw/main/Anno/EPIC/EPIC.hg38.manifest.tsv.gz")
> sdf = openSesame("EPIC/GSM2995280_201868590258_R01C01", prep="", func=NULL, manifest=addr)
> head(sesame:::negControls(sdf))
        UG  UR
865860 196 453
865861 203 346
865862 163 289
865864 199 258
865865 200 261
865866 202 336
> head(addr[grep("NEG",addr$Probe_ID),])
                    Probe_ID  M        U  col mask
865860 ctl_10609447_NEGATIVE NA 10609447 <NA> TRUE
865861 ctl_10627500_NEGATIVE NA 10627500 <NA> TRUE
865862 ctl_10676356_NEGATIVE NA 10676356 <NA> TRUE
865864 ctl_10731326_NEGATIVE NA 10731326 <NA> TRUE
865865 ctl_10732387_NEGATIVE NA 10732387 <NA> TRUE
865866 ctl_10740401_NEGATIVE NA 10740401 <NA> TRUE
```

**Comment by notmaurox** [comment]
Hi Wanding, thanks for pushing an update so quickly. However, I think the fix is not complete.

Your change properly returns a dataframe of the negative controls but in the detectionPnegECDF function, it expects the dataframe to have columns ['G', 'R'] not ['UG', 'UR']. As a result I am getting error 'Error in ecdf(negctls$G) : 'x' must have 1 or more non-missing values'

https://github.com/zwdzwd/sesame/blob/0fb810fbccd3633bd2bf534496a814693f5c5e25/R/detection.R#L52

https://github.com/zwdzwd/sesame/blob/0fb810fbccd3633bd2bf534496a814693f5c5e25/R/detection.R#L82

**Comment by zwdzwd** [comment]
Thanks @notmaurox. You are right. How about now?

https://github.com/zwdzwd/sesame/blob/b220a9a6439f226f2d76bf1cd4f7adc0b726b7d9/R/detection.R#L47

**Comment by notmaurox** [comment]
Looks good to me - things seem to be working on my end! 

Thanks for your help
