### ISSUE TITLE
Code for generating genomeInfo.mm10$txns?

### ISSUE THREAD

**Issue by Pancreas-Pratik** [zwdzwd/sesame#82]
Good morning @zwdzwd,

When you have some time, is there any way you could provide the code you used to generate the genomeInfo.mm10$txns, please?

I am trying to make an genomeInfo.mm39$txns. Your code https://github.com/zwdzwd/sesameData/issues/8#issuecomment-926125819 to determine the gapInfo and other files was really helpful for me in the past.

I am really looking forward to your response and help, Dr. Zhou.

Respectfully,
Pratik

EDIT: I edited this help request now after, maybe, sending it without thinking this morning before sleeping!

**Comment by zwdzwd** [comment]
Hi can you try

```
txns=sesameData:::build_GENCODE_gtf("https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M31/gencode.vM31.annotation.gtf.gz")
```

**Comment by Pancreas-Pratik** [comment]
Thank you very much Dr. Zhou, I actually have almost just finished doing it myself in a DIY kind of way. I'm pretty happy with how it turned out, it was a good exercise in `GenomicRanges` (I was actually right about to setup local loading on `sesameData` to try it!)  Let me try:




> 
> ```
> txns=sesameData:::build_GENCODE_gtf("https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M31/gencode.vM31.annotation.gtf.gz")
> ```

**Comment by Pancreas-Pratik** [comment]
Wow, I just tried, and it looks perfect @zwdzwd ! Thank you very much sir!
