### ISSUE TITLE
Turning off all probe masking

### ISSUE THREAD

**Issue by DolapoA** [zwdzwd/sesame#9]
Is there a way to turn off all forms of probe masking so that there are no NAs in the betas matrix? I would like to plot the densities of all betas including those that would have been masked.
So far I've used:

- `quality.mask = FALSE`

- `pval.threshold = 1*(10^18)`

- `pval.threshold = Inf`

**Comment by zwdzwd** [comment]
Hi,
Have you tried adding nondetection.mask = FALSE as well?

**Comment by DolapoA** [comment]
I use `openSesame()` and I just tried this but it didn't remove the mask:
`betas <- openSesame(x, nondetection.mask = FALSE, quality.mask = FALSE)`

**Comment by rauldiul** [comment]
I have had a similar issue, although using `openSesame()` with an `RGSet` object from minfi. I tried setting `pval.threshold` from 0.000001 to 1 and saw no change in the number of Masked Probes

**Comment by tiagochst** [comment]
```
sset <- sesameDataGet('HM450.1.TCGA.PAAD')$sset
IDATprefixes <- searchIDATprefixes(
     system.file("extdata", "", package = "sesameData"))
openSesame(IDATprefixes)  %>% is.na %>% table

openSesame(IDATprefixes, 
           quality.mask = FALSE, 
           nondetection.mask = FALSE, 
           mask.use.tcga = FALSE, 
           pval.threshold = 0.05, 
           sum.TypeI = FALSE)  %>% is.na %>% table
```

**Comment by zwdzwd** [comment]
With the new version (1.8+ and 1.9+, one can use getBetas(mask=FALSE) to turn off all masking. closing this issue now.
